### PR TITLE
devel: Adjust host factory for development

### PR DESCRIPTION
**Pull request by akofink**
I don't expect this to stay super stable, since it depends on the inventory's hosts table, which could change at any time, but for devel, this is still very useful to be able to create thousands of fake hosts, optionally in your own account.

```rb
User.current = User.new(account: Account.find_by(account_number: '123456')) # optional
FactoryBot.create(:host)
FactoryBot.create_list(:host, 1000)
```

Signed-off-by: Andrew Kofink <akofink@redhat.com>

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [X] Input Validation
- [X] Output Encoding
- [X] Authentication and Password Management
- [X] Session Management
- [X] Access Control
- [X] Cryptographic Practices
- [X] Error Handling and Logging
- [X] Data Protection
- [X] Communication Security
- [X] System Configuration
- [X] Database Security
- [X] File Management
- [X] Memory Management
- [X] General Coding Practices

### CODE REVIEW

File: test/factories/host.rb [hunk 1]
```diff
@@ -4,35 +4,73 @@
...
 
     transient do
-      os_major_version { 7 }
-      os_minor_version { 9 }
+      os_version do
+        ssg = SSGS.sample
+        [ssg.os_major_version.to_i, ssg.os_minor_version.to_i]
+      end
+      os_major_version { os_version[0] }
+      os_minor_version { os_version[1] }
```
Comment (akofink) [inline test/factories/host.rb:65]: I also decided to go ahead and make the OS dynamic based on what we have defined in supported_ssgs.yaml, since we often need different OS versions to test with (i.e. RHEL 6)

File: test/factories/host.rb [hunk 2]
```diff
@@ -4,35 +4,73 @@
...
+      system_profile do
+        system_profile_data
+      end
+    elsif Rails.env.development?
+      reporter { 'puptoo' }
+      modified_on { Time.zone.now }
+      facts { {} }
+      canonical_facts do
+        {
+          'fqdn' => Faker::Lorem.sentence
```
Comment (vkrizan) [inline test/factories/host.rb:50]: How about `Faker::Internet.domain_name`? I would maybe used it also for display_name (with the same value).

**Review by vkrizan — COMMENTED** [review]
Nice! I was impatient to have this host generation. Thank you.

There might be more that would need to be filled out for Inventory, so it does not raises exceptions when a new regular host is being registered.

File: test/factories/host.rb (hunk 2 above)
Comment (akofink) [reply test/factories/host.rb:50]: Thank you! I was looking for this :laughing:

**Review by vkrizan — APPROVED** [review]
Awesome!

**Comment by vkrizan** [comment]
```
 test_: update_hosts should add new hosts to an existing host set. #PolicyTest (45.12s)
Minitest::UnexpectedError:         NoMethodError: undefined method `version' for nil:NilClass
            app/models/supported_ssg.rb:45:in `latest_ssg_version_for_os'
            app/models/profile.rb:43:in `block in <class:Profile>'
            app/models/policy.rb:61:in `block in update_os_minor_versions'
            app/models/policy.rb:60:in `each'
            app/models/policy.rb:60:in `update_os_minor_versions'
            app/models/policy.rb:54:in `update_hosts'
            test/models/policy_test.rb:139:in `block (3 levels) in <class:PolicyTest>'
            test/models/policy_test.rb:138:in `block (2 levels) in <class:PolicyTest>'
            test/models/policy_test.rb:146:in `instance_exec'
            test/models/policy_test.rb:146:in `block in create_test_from_should_hash'
```

**Comment by akofink** [comment]
I'm still trying to figure out why the OS isn't being displayed in the inventory page:

image

**Comment by akofink** [comment]
Ok, I'm quite sure the test issue was caused by 7d51ec1. I was debugging it locally - it's kind of difficult because the issue is transient, but as soon as I reset my test DB after David's change, I can no longer reproduce the failure.
